apiVersion: v1
kind: Pod
metadata:
  name: model-service
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "demo"
    vault.hashicorp.com/agent-inject-secret-api-key: "secret/data/model-service"
spec:
  containers:
  - name: model-service
    image: your-docker-repo/model-inference:latest
